version: '3.8'

services:
  web:
    container_name: distributedwebof.care
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 4001:4000
    environnement:
      - PORT=4000
      - FLASK_DEBUG=1
